version: '3.8'

services:
  backend:
    container_name: challenge-2023-backend
    networks:
      - swag
      - databases
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      # - mongo
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
    
  frontend:
    container_name: challenge-2023
    networks:
      - swag
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        VITE_API_TIMEOUT: ${VITE_API_TIMEOUT}
        VITE_API: ${VITE_API}
        VITE_COOKIE_TOKEN_NAME: ${VITE_COOKIE_TOKEN_NAME}
        VITE_LAST_COMMIT: ${VITE_LAST_COMMIT}
    ports:
      - 8080:8080
    depends_on:
      backend:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      NODE_ENV: production
      VITE_API_TIMEOUT: ${VITE_API_TIMEOUT}
      VITE_API: ${VITE_API}
      VITE_COOKIE_TOKEN_NAME: ${VITE_COOKIE_TOKEN_NAME}
      VITE_LAST_COMMIT: ${VITE_LAST_COMMIT}
      
networks:
  swag:
    name: swag
    external: true
