version: '3.8'

services:
  backend:
    container_name: challenge-2023-backend
    networks:
      - swag
      - database
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      # - mongo
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
    
  frontend:
    container_name: challenge-2023
    networks:
      - swag
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      backend:
        condition: service_healthy
    environment:
      VITE_API: ${API}
      VITE_API_TIMEOUT: ${API_TIMEOUT}
      VITE_COOKIE_TOKEN_NAME: $COOKIE_TOKEN_NAME}
      NODE_ENV: production

networks:
  swag:
    name: swag
    external: true
