version: '3.8'

services:
  postgres:
    ports:
      - 5432:5432

  mongo:
    ports:
      - 27017:27017

  # Equivalent of phpmyadmin but for mongodb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8085:8081
    depends_on:
      - mongo
    networks:
      - databases
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
