version: '3.8'
services:
  # backend:
  #   image: node
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - mongo

  # mongo:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ADMIN_USERNAME}:${MONGO_ADMIN_PASSWORD}@mongo:27017/
  #   volumes:
  #     - ./db-data:/data/db

  posgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      # POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_USER: root
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    
  # frontend:
  #   image: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend
  