name: Github sanity check
run-name: ${{ github.actor }} launching Github sanity check

on:
  push:
    branches: [ main ]

jobs:
  verified_commit_check:
    name: Check for verified commits
    runs-on: ubuntu-latest
    steps:
      - uses: nadock/verified_commits_check@main
